export const groupIntentions = {
  title: "Zbiorowa",
  date: "22.10.2025r.",
  intentions: [
    "- w intencji dobroczyńców naszego kościoła",
    "- w intencji naszej Ojczyzny",
    "- w intencji apostolatu Margaretka w naszej parafii",
    "- w intencji pań które sprzątają i opiekują się otoczeniem kościoła i prac. w Bibliotece Parafialnej",
    "- o wyzwolenie z nałogu",
    "+Romualda Bajorskiego, Andrzeja /4 r. śm./, Zofię, Kazimierza Kościelnych, Jana Sobczaka",
    "+Zbigniewa, Jana Kaletów",
    "+Jerzego Walaszczyka /od uczest. pogrzebu/",
    "+Halinę Urban /od uczest. pogrzebu/",
    "+Jacka Biernackiego /od uczest. pogrzebu/",
    "+Mieczysława Kempę /od uczest. pogrzebu/",
    "+Genowefę Wilk /od uczest. pogrzebu/",
    "+Józfa Krygiera /od uczest. pogrzebu/",
    "+Zygmunta Nicponia /od Zakładu Pogrzebowego Calla/",
    "+Marię Kozłowską /od koleżanek z Koła Gospodyń/",
    "+ Marię Kasprzyk /od sąsiadów z klatki i znajomych/",
    "+Marię Okularczyk /od brata Marka z rodz./",
    "+Marka Rzońce /od uczest. pogrzebu/",
    "+Konrada Mastalerza /od sąsiadów z ul. Parkowej/",
    "+Franciszka Merdzika /od uczest. pogrzebu/",
    "+Henrykę Pyrkosz /od Bożeny - koleżanki córki/",
    "+Macieja Lewandowskiego /od uczest. pogrzebu/",
    "+Eulalię Gruca /od Jana Grucy z rodz./",
    "+Józefa, Stanisławę Idziaków",
    "+Krystynę Knop /od Krzysztofa Jaska i Anny, Jana Witkowskich/",
    "+Waldemara Gębusia /od żony Elżbiety z dziećmi i wnukami/",
    "+Helenę Makles /od synów z rodzinami/",
    "+Urszulę Lewandowską /od córki i zięcia/",
    "+Mieczysława, Roberta Nowiszewskich",
  ],
};
