export const groupIntentions = {
  title: "Msza zbiorowa",
  date: "03.01.2025r.",
  intentions: [
    "- w int. ofiarodawców na rzecz naszego kościoła",
    "- w int. uczestników apostolatu „Margaretka” w naszej parafii",
    "- w int. pań, które sprzątają i opiekują się otoczeniem kościoła",
    "- o nawrócenie Polski i świata",
    "- o zdrowie dla Eweliny",
    "+Małgorzatę Pacuła /od Janiny Marchewka/",
    "+Zofię Pienias /od uczest. pogrzebu/",
    "+Barbarę Kołodziejczyk /od Danuty i Waldemara Brendzel/",
    "+Mirosława Rakusa /od rodz. Kasprzyków/",
    "+Ingę Zawadzką /od uczest. pogrzebu/",
    "+Zdzisława, Zygmunta Pydów",
    "+Waldemara Gębusia /od Jerzego Michalika z rodz./",
    "+Sylwestra Lamcha /od Kazimierza, Mirosława i Stanisława Lamchów z rodzinami/",
    "+Sabinę Sowa /od sąsiadów Jagusiaków i Bekusów/",
    "+Roberta Nowiszewskiego /od koleżanek mamy/",
    "+Kazimierę Kulejewską /od uczest. pogrzebu/",
    "+Annę Mularz /od uczest. pogrzebu/",
    "+Ryszarda Chłonda /od sąsiadów z klatki i rodz. Soszyńskich/",
    "+Mariana Kicińskiego /od Haliny Głąb z Przyrowa i córek Marioli i Basi z rodz./",
    "+Elżbietę Borowską /od kuzynki Teresy Kubiś z rodz./",
    "+Mirosława Korbla /od rodz. Kołacz/",
    "+Irenę Gwieździńską /od uczest. pogrzebu/",
    "+Jana Korbuta /od rodz. Gliców/",
    "+Waldemara Kurzacza /od rodz. Kurzacz, Koperów i Szczepańskich/",
    "+Teresę Kępa /od siostry Heni i Jadzi z rodzinami/",
    "+Teresę Żurek /od przyjaciółki Wandy/",
    "+Andrzeja Bryłę /od syna Rafała z żoną i wnukiem Kacprem/",
    "+Mariana Kasprzyka /od rodz. Koperskich i Nowaków/",
    "+Zbigniewa Paruzela /14 r. śm./, Krystynę, Franciszka i Andrzeja Jaseckich",
    "+Wiesławę Lupa /1 r. śm./",
  ],
};
