export const groupIntentions = {
  title: "Zbiorowa",
  date: "06.08.2025r.",
  intentions: [
    "- w intencji dobroczyńców naszego kościoła",
    "- w intencji naszej Ojczyzny",
    "- w intencji apostolatu Margaretka w naszej parafii",
    "- w intencji pań które sprzątają i opiekują się otoczeniem kościoła i prac. w Bibliotece Parafialnej",
    "- o wyzwolenie z nałogu",
    "+Marikę Domsha /od uczest. pogrzebu/",
    "+Zofię /12 r.śm./, Kazimierza, Andrzeja Kościelnych, Jana Sobczaka, Romualda Bojarskiego,",
    "Henrykę Goleszyńską",
    "+Elwirę Mszyca /od uczest. pogrzebu/",
    "+Henryka Ludwika /od kolegów/",
    "+Teresę Pilawka /od siostrzeńca Karola/",
    "+Henrykę Chłond /od uczest. pogrzebu/",
    '+Jerzego Walaszczyka /od koleżanek i kolegów z firmy "Ekomex - Pilśnia/',
    "+Halinę Urban /od koleżanek córki Bożeny - Marioli, Jadzi, Małgosi i Beaty/",
    "+Ryszarda Hiszpańskiego /od uczest. pogrzebu/",
    "+Krystynę Pyda /od wnuczki Marleny z rodz./",
    "+Genowefę Andrzejczak /od Elżbiety i Adama Napierajów z rodz./",
    "+Jacka Biernackiego /od koleżanek i kolegów ze Szkoły Podstawowej nr 1/",
    "+Marię Przygoda /od Beaty Szymczyk z synami/",
    "+Mieczysława Kempę /od chrześniaka Marcina Kostki z rodz./",
    "+Macieja Lewandowskiego /od rodz. Gruszków z Zakopanego/",
    "+Janusza Zalejskiego /od Alicji i Ewy Mieszkowskich/",
    "+Lecha, Annę Gębusiów /od sąsiadów/",
    "+Henryka Jachimczaka /od rodz. Gajlewiczów/",
    "+Janinę Rykała /od rodziny/",
    "+Genowefę Wilk /od Alfredy Bulskiej/",
    "+Józefa Krygliel /od Haliny i Basi z rodz./",
    "+Aldonę Pielińską /od Wioletty Talaga z rodz./",
    "+Mariana Gawora /od Heleny Wieczorek - Podsiedlik z rodz./",
  ],
};
